### ISSUE TITLE
App Crashes when deleting an entry with a PR

### ISSUE THREAD

**Issue by gruberjl** [gruberjl/LinearLifts#21]
ava.lang.NullPointerException: Attempt to invoke virtual method 'long pro.wildbeast.wildbeastfitness.models.Pr.get_id()' on a null object reference at pro.wildbeast.wildbeastfitness.models.Entry.setPr(Entry.java:73) at pro.wildbeast.wildbeastfitness.models.Entry.resyncPr(Entry.java:187) at pro.wildbeast.wildbeastfitness.entry.page.EntriesAdapter.remove(EntriesAdapter.java:43) at pro.wildbeast.wildbeastfitness.entry.page.EntryViewHolder$3.onClick(EntryViewHolder.java:60) at android.view.View.performClick(View.java:4780) at android.view.View$PerformClick.run(View.java:19866) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5254) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by gruberjl** [comment]
I was unable to reproduce issue. I added code that handles the null reference.
